# Generated by Django 5.2.1 on 2025-06-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellido', 'nombre']},
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(help_text='13 Caracteres', max_length=13, unique=True, verbose_name='ISBN'),
        ),
    ]
