# Generated by Django 5.2.1 on 2025-06-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_autor_options_alter_libro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.ManyToManyField(help_text='Seleccione un género para este libro', related_name='generos', to='catalogo.genero'),
        ),
    ]
